* This emacs config is based on https://github.com/redguardtoo/emacs.d.git
** The following modification has been made for C/C++ development:
- added some useful pacakges, such as projectile and helm-projectile 
- added some useful customizing functions and useful key bind, mainly in .custom.el
- some minor changes, such as color for better display and optimization for Windows
* Before start
Please read below checklist for at least once
- I recommend *Emacs 24.3.1*
- Get Git installed
- Plugins/Packages from [[http://melpa.org][melpa-unstable]] are *invisible* by default. Modify variable *melpa-include-packages* in init-elpa.el if you need any of them
- Any other issues are covered in FAQ
* Installation
The installation suits both Windows and Linux. 
For Windows user, please specify the proper home directory in evironment variable HOME. The default HOME in windows is C:\user\youruser\Roaming

Please remove the file "$HOME/.emacs.d/init.el" if it presents

Go to the home directory and run the following command:
git clone https://github.com/xjhpaopao/emacs.d.git .emacs.d"

Ensure that the init.el contained in this repo ends up at ~/.emacs.d/init.el.

You *possibly* need run below command at the terminal at least once to update the content from package repositories:
#+BEGIN_SRC elisp
emacs -nw --batch -l ~/.emacs.d/init.el -f package-refresh-contents
#+END_SRC

The command "package-refresh-content" will fetch the latest package list from remote servers. It has to be done manually. It's not reasonable to *automatically* fetch the list during a text editor startup. 
* Tutorial (OPTIONAL)
** Basic tutorial
*** Step 1, learn OS basics
Read wikipedia in order to know,
- What is environment variable
- What is pipe, stdout, stdin
*** Step 2, read official tutorial at least once
Press "C-h t" ("C" means Ctrl) to read bundled tutorial.

At minimum you need know:
- How to move cursor
- How to read help by pressing "C-h v" and "C-h f".
* FAQ
** GUI version has issues?
Use terminal version.
** OS X user?
Please remove bundled emacs 22 at first!

You may need remove the obsolete ctags/etags too.
** Why certain plugins cannot be upgraded through ELPA?
Some plugins (Evil, Helm, Web-mode ...) are so important to my workflow that I locked their versions.
** C++ developers?
You need set up the directories to seach C++ header files. Please see the section `clang`.
** [[http://melpa.org][MELPA]] does not include the plugin?
If a plugin is not installable through MELPA, you can place it at ~/.emacs.d/site-lisp. There are already some samples there.
** Non-English users?
Please make sure your locale is *UTF-8 compatible*. For example, if I type `locale` in shell, I will get the  output "zh_CN.UTF-8". If and only if you see the "UTF-8", your locale is correct.
** Your government blocks the internet?
People in (China, North Korea, Cuba, Iran ...) need [[http://code.google.com/p/goagent/][goagent]] to download packages. Run command line "http_proxy=http://127.0.0.1:8087 emacs -nw" in shell after starting goagent server
** Email setup?
If you use Gnus for email (Gmail, for example), check init-gnus.el. Then read [[http://blog.binchen.org/?p=403][my Gnus tutorial]].
** How to toggle Chinese input method?
Run command `M-x toggle-input-method`.
** Cannot download packages through ELPA?
Some package cannot be downloaded automatically because of network problem.

You need manually `M-x list-packages` and install it or `M-x package-refresh-content` and restart Emacs.

** Use Emacs key bindings instead of Vim key bindings
By default EVIL (Vim emulation in Emacs) is used. You can comment out line containing "(require 'init-evil)" in init.el to unload it.

** Evil setup
It's defined in "init-evil.el". You can press "C-z" to switch between Emacs and Vim key bindings in evil-mode.

Please reading [[https://gitorious.org/evil/evil/blobs/raw/doc/doc/evil.pdf][its PDF manual]] before using evil-mode.

** Use color theme in the terminal
#+BEGIN_SRC sh
TERM=xterm-256color emacs -nw
#+END_SRC

** Avoid Emacs maximized when it starts up
Comment out below line in init-misc.el:
#+BEGIN_SRC elisp
(add-hook 'window-setup-hook 'maximize-frame t)
#+END_SRC

** Preview&apply a color theme?
Check [[http://emacsthemes.caisah.info/]].

Write down the name of color theme (for example, molokai).

Insert below code into ~/.emacs.d/init.el,
#+BEGIN_SRC elisp
(require 'color-theme-molokai)
(color-theme-molokai)
#+END_SRC

"M-x color-theme-select" may not work in this setup. It's because of some design flaw in Emacs.

** Directory structure
init.el is the main file. It includes all the other *.el files.

"init-elpa.el" defines how and what packages will be installed from [[http://melpa.org][MELPA]].

The package manager will extract packages into ~/.emacs.d/elpa/.

I also manually download and extract some packages into ~/.emacs.d/site-lisp/. Packages in ~/.emacs.d/site-lisp/ is not visible to the package manager.

My own snippets for [[https://github.com/capitaomorte/yasnippet][Yasnippet]] is at ~/.emacs.d/snippets.

customized configuration is in .custom.el

Other directories don't matter.

** About Emacs 23
Emacs 23 support will *be dropped* on <2015-04-24 Thu>.
Currently below plugins are not supported on Emacs 23:
- helm
- org-mode and its plugins
- company-mode
- git-gutter
- yasnippet
- ggtags-mode
